"""
This type stub file was generated by pyright.
"""

from .windowcontroller import WindowController

"""
Controllers
===========

.. versionadded:: 1.0.0

Modules and classes that implement useful methods for getting information
about the state of the current application window.
"""
