"""
This type stub file was generated by pyright.
"""

from .androidtoast import toast

"""
Toast for Android device
========================

.. image:: https://github.com/HeaTTheatR/KivyMD-data/raw/master/gallery/kivymddoc/toast.png
    :align: center

"""
__all__ = ("toast", )
