"""
This type stub file was generated by pyright.
"""

from kivy.uix.modalview import ModalView
from kivymd.theming import ThemableBehavior
from kivymd.uix.behaviors import CommonElevationBehavior, MotionDialogBehavior

"""
Components/Dialog
=================

.. seealso::

    `Material Design spec, Dialogs <https://material.io/components/dialogs>`_


.. rubric:: Dialogs inform users about a task and can contain critical
    information, require decisions, or involve multiple tasks.

.. image:: https://github.com/HeaTTheatR/KivyMD-data/raw/master/gallery/kivymddoc/dialogs.png
    :align: center

Usage
-----

.. code-block:: python

    from kivy.lang import Builder

    from kivymd.app import MDApp
    from kivymd.uix.button import MDFlatButton
    from kivymd.uix.dialog import MDDialog

    KV = '''
    MDFloatLayout:

        MDFlatButton:
            text: "ALERT DIALOG"
            pos_hint: {'center_x': .5, 'center_y': .5}
            on_release: app.show_alert_dialog()
    '''


    class Example(MDApp):
        dialog = None

        def build(self):
            self.theme_cls.theme_style = "Dark"
            self.theme_cls.primary_palette = "Orange"
            return Builder.load_string(KV)

        def show_alert_dialog(self):
            if not self.dialog:
                self.dialog = MDDialog(
                    text="Discard draft?",
                    buttons=[
                        MDFlatButton(
                            text="CANCEL",
                            theme_text_color="Custom",
                            text_color=self.theme_cls.primary_color,
                        ),
                        MDFlatButton(
                            text="DISCARD",
                            theme_text_color="Custom",
                            text_color=self.theme_cls.primary_color,
                        ),
                    ],
                )
            self.dialog.open()


    Example().run()

.. image:: https://github.com/HeaTTheatR/KivyMD-data/raw/master/gallery/kivymddoc/alert-dialog.png
    :align: center
"""
__all__ = ("MDDialog", "BaseDialog")
class BaseDialog(ThemableBehavior, MotionDialogBehavior, ModalView, CommonElevationBehavior):
    elevation = ...
    shadow_softness = ...
    shadow_offset = ...
    radius = ...
    _scale_x = ...
    _scale_y = ...


class MDDialog(BaseDialog):
    """
    Dialog class.

    For more information, see in the
    :class:`~kivymd.theming.ThemableBehavior` and
    :class:`~kivy.uix.modalview.ModalView` and
    :class:`~kivymd.uix.behaviors.CommonElevationBehavior`
    classes documentation.
    """
    title = ...
    text = ...
    buttons = ...
    items = ...
    width_offset = ...
    type = ...
    content_cls = ...
    md_bg_color = ...
    _scroll_height = ...
    _spacer_top = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def update_width(self, *args) -> None:
        ...
    
    def update_height(self, *args) -> None:
        ...
    
    def update_items(self, items: list) -> None:
        ...
    
    def on_open(self) -> None:
        ...
    
    def get_normal_height(self) -> float:
        ...
    
    def edit_padding_for_item(self, instance_item) -> None:
        ...
    
    def create_items(self) -> None:
        ...
    
    def create_buttons(self) -> None:
        ...
    


