"""
This type stub file was generated by pyright.
"""

import os
import kivy
import kivymd.factory_registers
import kivymd.font_definitions
from kivy.logger import Logger
from kivymd._version import __date__, __hash__, __short_hash__
from kivymd.tools.packaging.pyinstaller import hooks_path

"""
KivyMD
======

.. image:: https://github.com/HeaTTheatR/KivyMD-data/raw/master/gallery/previous.png

Is a collection of Material Design compliant widgets for use with,
`Kivy cross-platform graphical framework <http://kivy.org/#home>`_
a framework for cross-platform, touch-enabled graphical applications.
The project's goal is to approximate Google's `Material Design spec
<https://material.io/design/introduction>`_ as close as possible without
sacrificing ease of use.

This library is a fork of the `KivyMD project
<https://gitlab.com/kivymd/KivyMD>`_. We found the strength and brought this
project to a new level.

If you wish to become a project developer (permission to create branches on the
project without forking for easier collaboration), have at least one PR
approved and ask for it. If you contribute regularly to the project the role
may be offered to you without asking too.
"""
__version__ = ...
release = ...
path = ...
fonts_path = ...
images_path = ...
uix_path = ...
glsl_path = ...
_log_message = ...
