"""
This type stub file was generated by pyright.
"""

"""
Themes/Color Definitions
========================

.. seealso::

   `Material Design spec, The color system <https://material.io/design/color/the-color-system.html>`_

   `Material Design spec, The color tool <https://material.io/resources/color/#!/?view.left=0&view.right=0>`_

Material colors palette to use in :class:`kivymd.theming.ThemeManager`.
:data:`~colors` is a dict-in-dict where the first key is a value from
:data:`~palette` and the second key is a value from :data:`~hue`. Color is a hex
value, a string of 6 characters (0-9, A-F) written in uppercase.

For example, ``colors["Red"]["900"]`` is ``"B71C1C"``.
"""
colors = ...
palette = ...
hue = ...
light_colors = ...
text_colors = ...
theme_colors = ...
