"""
This type stub file was generated by pyright.
"""

"""
Themes/Font Definitions
=======================

.. seealso::

   `Material Design spec, The type system <https://material.io/design/typography/the-type-system.html>`_
"""
fonts = ...
theme_font_styles = ...
