"""
This type stub file was generated by pyright.
"""

from typing import List
from kivy.uix.label import Label
from kivymd.uix.dialog import BaseDialog

"""
KivyToast
=========

.. rubric:: Implementation of toasts for desktop.

.. code-block:: python

    from kivy.lang import Builder

    from kivymd.app import MDApp
    from kivymd.toast import toast

    KV = '''
    MDScreen:

        MDTopAppBar:
            title: 'Test Toast'
            pos_hint: {'top': 1}
            left_action_items: [['menu', lambda x: x]]

        MDRaisedButton:
            text: 'TEST KIVY TOAST'
            pos_hint: {'center_x': .5, 'center_y': .5}
            on_release: app.show_toast()
    '''


    class Test(MDApp):
        def show_toast(self):
            '''Displays a toast on the screen.'''

            toast('Test Kivy Toast')

        def build(self):
            return Builder.load_string(KV)

    Test().run()
"""
class Toast(BaseDialog):
    duration = ...
    _md_bg_color = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def label_check_texture_size(self, instance_label: Label, texture_size: List[int]) -> None:
        """
        Resizes the text if the text texture is larger than the screen size.
        Sets the size of the toast according to the texture size of the toast
        text.
        """
        ...
    
    def toast(self, text_toast: str) -> None:
        """Displays a toast."""
        ...
    
    def on_open(self) -> None:
        """Default open event handler."""
        ...
    
    def fade_in(self) -> None:
        """Animation of opening toast on the screen."""
        ...
    
    def fade_out(self, *args) -> None:
        """Animation of hiding toast on the screen."""
        ...
    
    def on_touch_down(self, touch): # -> bool:
        ...
    


def toast(text: str = ..., background: list = ..., duration: float = ...) -> None:
    """
    Displays a toast.

    :param text: text to be displayed in the toast;
    :param duration: the amount of time (in seconds) that the toast is visible on the screen
    :param background: toast background color in ``rgba`` format;
    """
    ...

