"""
This type stub file was generated by pyright.
"""

import types

"""
asynckivy
=========

Copyright (c) 2019 Nattōsai Mitō

GitHub -
    https://github.com/gottadiveintopython
GitHub Gist -
    https://gist.github.com/gottadiveintopython/5f4a775849f9277081c396de65dc57c1

"""
__all__ = ("start", "sleep", "event")
CallbackParameter = ...
def start(coro): # -> None:
    ...

@types.coroutine
def sleep(duration): # -> Generator[(step_coro: Unknown) -> Unknown, Unknown, Unknown]:
    ...

class event:
    def __init__(self, ed, name) -> None:
        ...
    
    def bind(self, step_coro): # -> None:
        ...
    
    def callback(self, *args, **kwargs): # -> None:
        ...
    
    def __await__(self): # -> Generator[(step_coro: Unknown) -> None, Any, CallbackParameter]:
        ...
    


