"""
This type stub file was generated by pyright.
"""

from kivymd.uix.behaviors.stencil_behavior import StencilBehavior

"""
Behaviors/Motion
================

.. rubric:: Use motion to make a UI expressive and easy to use.

.. image:: https://github.com/HeaTTheatR/KivyMD-data/raw/master/gallery/kivymddoc/motion.png
    :align: center

.. versionadded:: 1.2.0

Classes of the `Motion` type implement the display behavior of widgets such
as dialogs, dropdown menu, snack bars, and so on.
"""
__all__ = ("MotionBase", "MotionDropDownMenuBehavior", "MotionDialogBehavior", "MotionShackBehavior")
class MotionBase:
    """Base class for widget display movement behavior."""
    show_transition = ...
    show_duration = ...
    hide_transition = ...
    hide_duration = ...


class MotionDropDownMenuBehavior(MotionBase):
    """
    Base class for the dropdown menu movement behavior.

    For more information, see in the :class:`~MotionBase` class documentation.
    """
    show_transition = ...
    show_duration = ...
    hide_transition = ...
    _scale_x = ...
    _scale_y = ...
    _opacity = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def set_opacity(self) -> None:
        ...
    
    def set_scale(self) -> None:
        ...
    
    def on_dismiss(self) -> None:
        ...
    
    def on_open(self, *args): # -> None:
        ...
    
    def on__opacity(self, instance, value): # -> None:
        ...
    
    def on__scale_x(self, instance, value): # -> None:
        ...
    
    def on__scale_y(self, instance, value): # -> None:
        ...
    


class MotionDialogBehavior(MotionBase):
    """
    Base class for dialog movement behavior.

    For more information, see in the :class:`~MotionBase` class documentation.
    """
    show_duration = ...
    scale_x = ...
    scale_y = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def set_default_values(self): # -> None:
        """Sets default scaled and transparency values."""
        ...
    
    def on_dismiss(self, *args): # -> None:
        """Called when a dialog closed."""
        ...
    
    def on_open(self, *args): # -> None:
        """Called when a dialog opened."""
        ...
    


class MotionShackBehavior(StencilBehavior, MotionBase):
    """
    The base class for the behavior of the movement of snack bars.

    For more information, see in the
    :class:`~MotionBase` class and
    :class:`~kivy.uix.behaviors.stencil_behavior.StencilBehavior` class
    documentation.
    """
    _interval = ...
    _height = ...
    def on_dismiss(self, *args): # -> None:
        """Called when a snackbar closed."""
        ...
    
    def on_open(self, *args): # -> None:
        """Called when a snackbar opened."""
        ...
    


