"""
This type stub file was generated by pyright.
"""

"""
Behaviors/Touch
===============

.. rubric:: Provides easy access to events.

The following events are available:

- on_long_touch
- on_double_tap
- on_triple_tap

Usage
-----

.. code-block:: python

    from kivy.lang import Builder

    from kivymd.app import MDApp
    from kivymd.uix.behaviors import TouchBehavior
    from kivymd.uix.button import MDRaisedButton

    KV = '''
    Screen:

        MyButton:
            text: "PRESS ME"
            pos_hint: {"center_x": .5, "center_y": .5}
    '''


    class MyButton(MDRaisedButton, TouchBehavior):
        def on_long_touch(self, *args):
            print("<on_long_touch> event")

        def on_double_tap(self, *args):
            print("<on_double_tap> event")

        def on_triple_tap(self, *args):
            print("<on_triple_tap> event")


    class MainApp(MDApp):
        def build(self):
            return Builder.load_string(KV)


    MainApp().run()
"""
__all__ = ("TouchBehavior", )
class TouchBehavior:
    duration_long_touch = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def create_clock(self, widget, touch, *args): # -> None:
        ...
    
    def delete_clock(self, widget, touch, *args): # -> None:
        ...
    
    def on_long_touch(self, touch, *args): # -> None:
        """Called when the widget is pressed for a long time."""
        ...
    
    def on_double_tap(self, touch, *args): # -> None:
        """Called by double clicking on the widget."""
        ...
    
    def on_triple_tap(self, touch, *args): # -> None:
        """Called by triple clicking on the widget."""
        ...
    


