"""
This type stub file was generated by pyright.
"""

from kivy.utils import platform
from .androidtoast import toast
from .kivytoast import toast

__all__ = ("toast", )
if platform == "android":
    ...
else:
    ...
